docs: add Immutable Tags article
project-zot/project-zot.github.io pull request #165
Opened 2024-03-17 07:09 UTC by nvtkaszpir

Fixes #164

**What type of PR is this?**

**Which issue does this PR fix**:
#164 

**What does this PR do / Why do we need it**:
Easier to find content without searching

**If an issue # is not available please add repro steps and logs showing the issue**:

**Testing done on this change**:

**Automation added to e2e**:

**Will this break upgrades or downgrades?**

**Does this PR introduce any user-facing change?**:

```release-note

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-03-17 21:53 UTC, rchincha approved these changes
lgtm

2024-03-17 21:54 UTC, rchincha requested changes
@nvtkaszpir can you also pls sign your commit?

2024-03-17 23:11 UTC, nvtkaszpir commented
but it is already?

2024-03-18 06:06 UTC, andaaron approved these changes

2024-03-18 21:19 UTC, merged